### ISSUE TITLE
Feature: Pass Credentials for OCR-D Container

### ISSUE THREAD

**Issue by M3ssman** [ulb-sachsen-anhalt/ocrd-odem#13]
# Description

When executing containerized actions, we do not consider the use case if the actual executing account *might not* be related to productive `ocr` accounts on worker machines, where OCR-Generation *usually* runs.

In case of ODEM, it's quite pain if ODEM is part of a larger evaluation pipeline run by automated agents (like gitlab-runner) and needs to access other realms of the file system. When doing so, the process stops by now, since the user identifications don't match and the agent is not allowed to overwrite data produced by other accounts. 

Instead of just using the current user's ids in `processing_ocrd.py:79` please pass new config value `ocrd_container_user` from `odem.ini` with the current implementation as fallback if no user has been explicitly configured.

**Comment by einspunktnull** [comment]
@M3ssman: check impl: 0dab65e
