### ISSUE TITLE
Feature: Pass Language Models with different text orientation

### ISSUE THREAD

**Issue by M3ssman** [ulb-sachsen-anhalt/ocrd-odem#14]
# Description

Currently, the list of Tesseract language models which require special text orientation, is a hard-coded list in `odem_commons.p:71` as `RTL_LANGUAGES`.

This doesn't work of course for any self-trained model which is not known forehand.

Please integrate a config option like `model_rtl = ara, fas, heb` and respect it's values at `processing_ocrd.py#get_recognition_level` , if set. 

Otherwise use the common constant (see above) as default value.

**Comment by einspunktnull** [comment]
check it
