### ISSUE TITLE
Threading inconsistency

### ISSUE THREAD

**Issue by M3ssman** [ulb-sachsen-anhalt/ocrd-odem#23]
# Description

For larger loads (+700 pages, several hours runtime) the monitoring run-call seems to fall into sleep and won't return properly anymore.
This results in the workflow to halt until eternity.

Probably related to Python 3.10 threading, internal refactoring of monitor package or to some related libraries; 
unclear

**Comment by sVnsation** [comment]
Sehr geehrte Damen und Herren,

vielen Dank für Ihre Nachricht.

Ab dem 08.07.2024 bin ich wieder erreichbar. Ihre Nachricht wird nicht automatisch weitergeleitet.

In dringenden Angelegenheiten wenden Sie sich bitte an Thomas Hoffmann, E-Mail: ***@***.***, Tel. 0345 55 22146.

--
Mit freundlichen Grüßen

Sven Naumann
Abteilung "IT & Digitale Dienste"

Telefon: +49 (0)345 55 - 22191
E-Mail: ***@***.***

Hausadresse:
Martin-Luther-Universität Halle-Wittenberg
Universitäts- und Landesbibliothek Sachsen-Anhalt (ULB)
August-Bebel-Str. 13, Raum 224
06108 Halle (Saale)
----------------------------------

>>> Uwe Hartwig ***@***.***> 28.6.24 13:45 >>>

# Description

For larger loads (+700 pages, several hours runtime) the monitoring run-call seems to fall into sleep and won't return properly anymore.
This results in the workflow to halt until eternity.

Probably related to Python 3.10 threading, internal refactoring of monitor package or to some related libraries; 
unclear

-- 
Reply to this email directly or view it on GitHub:
https://github.com/ulb-sachsen-anhalt/ocrd-odem/issues/23

**Comment by M3ssman** [comment]
Stays unclear, a workaround is provided via config flag that disables wrapped execution via `[monitoring] live = False`
